spring:
  datasource:
    url: jdbc:postgresql://commerce-postgresql.cv0262ui2g6f.ap-northeast-2.rds.amazonaws.com:5432/postgres
    username: postgre
    password: tidlsl!2
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
