# test1
name: Deploy to EC2
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}
    - name: Deploy to EC2
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" -p ./build/libs/commerce-back-0.0.1.jar ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:commerce-back/
    - uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          cd commerce-back
          java -jar commerce-back-0.0.1.jar
  
    

        
